### ISSUE TITLE
іменування

### ISSUE THREAD

**Issue by pecourses** [Jaykob2447/React#1]
https://github.com/Jaykob2447/React/blob/7eab2bdf26f78a02a65b41b7f16ebe6f5dce5bd3/intro/src/userCard/index.jsx#L7
- функцію для зміни стану рекомендується іменувати як і стан, тільки з дієсловом set:
```javascript
  const [followersCount, setFollowersCount] = useState(followers);
```

**Comment by pecourses** [comment]
https://github.com/Jaykob2447/React/blob/7eab2bdf26f78a02a65b41b7f16ebe6f5dce5bd3/intro/src/userCard/index.jsx#L4
- компонент, його папку і стилі прийнято іменувати однаково, наприклад, `UserCard` або `Card`. Стилі, відповідно, будуть, _UserCard.css_ або _Card.css_. В подальшому рекомендується використовувати модулі стилів, щоб уникнути небажаних конфліктів стилів.

**Comment by Jaykob2447** [comment]
add commit

**Comment by pecourses** [comment]
https://github.com/Jaykob2447/React/commit/8153b760e3df6ad7e41c03b002fd70f6d1f1a9a9#r150483314
