### ISSUE TITLE
повноекранний режим

### ISSUE THREAD

**Issue by pecourses** [Jaykob2447/React#3]
https://github.com/Jaykob2447/React/blob/7eab2bdf26f78a02a65b41b7f16ebe6f5dce5bd3/intro/src/userCard/index.jsx#L19
- щоб довести справу до логічного завершення, можна додати відповідний стан, типу `isFullScreen`, міняти його при натисканні на картку, і в залежності від нього навішувати/не навішувати клас

**Comment by Jaykob2447** [comment]
add commit
