### ISSUE TITLE
користувач

### ISSUE THREAD

**Issue by pecourses** [Jaykob2447/React#4]
https://github.com/Jaykob2447/React/blob/7eab2bdf26f78a02a65b41b7f16ebe6f5dce5bd3/intro/src/userCard/index.jsx#L44
https://github.com/Jaykob2447/React/blob/7eab2bdf26f78a02a65b41b7f16ebe6f5dce5bd3/intro/src/userCard/index.jsx#L48
- логічно було б запакувати інфу про користувача у відповідний об'єкт і передавати в пропсах

**Comment by Jaykob2447** [comment]
add commit
