### ISSUE TITLE
іменування

### ISSUE THREAD

**Issue by pecourses** [Jaykob2447/React#7]
https://github.com/Jaykob2447/React/blob/e692beecbf245053bfc4780cbda8ddc18f29b9e4/intro/src/components/store/index.js#L6
https://github.com/Jaykob2447/React/blob/e692beecbf245053bfc4780cbda8ddc18f29b9e4/intro/src/components/store/slices/TodoSlice.js#L4
- імена властивостей об'єктів прийнято іменувати в lowerCamelCase, тобто 
```javascript
 reducer: { favorite: favoriteReducer, todo: todo }, 
``` 
---
https://github.com/Jaykob2447/React/blob/e692beecbf245053bfc4780cbda8ddc18f29b9e4/intro/src/components/store/slices/TodoSlice.js#L18
- це не клас і не функція конструктор, тому варто іменувати з маненької літери: `todoSlice`

**Comment by pecourses** [comment]
https://github.com/Jaykob2447/React/blob/e692beecbf245053bfc4780cbda8ddc18f29b9e4/intro/src/components/store/slices/TodoSlice.js#L4
- код легше сприймається, якшо іменувати масиви за загальноприйнятою домовленістю в множині

**Comment by Jaykob2447** [comment]
add commit
