### ISSUE TITLE
стора

### ISSUE THREAD

**Issue by pecourses** [Jaykob2447/React#8]
https://github.com/Jaykob2447/React/blob/e692beecbf245053bfc4780cbda8ddc18f29b9e4/intro/src/components/store/index.js#L6
- папку зі сторою логічно буде зберігати на одному рівні з `components`, а не в `components`
- редюсери краще іменувати однотипно, тоді в коду буде легше розбиратися при підтримці:
```javascript
 reducer: { favorite: favoriteReducer, todo: todoReducer }, 
```

**Comment by Jaykob2447** [comment]
add commit
