### ISSUE TITLE
генерація id

### ISSUE THREAD

**Issue by pecourses** [Jaykob2447/React#9]
https://github.com/Jaykob2447/React/blob/e692beecbf245053bfc4780cbda8ddc18f29b9e4/intro/src/components/TodoApp/index.jsx#L10
- при такому способі формування `id`, якщо видалити не останню і знову створити таску, то буде дублюватися `id`, а отже `key` у компонентів (що не є добре для реакт). Краще використовувати `uuid`, або, на крайняк, навіть `Date.now()`

**Comment by Jaykob2447** [comment]
add commit
